### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by o-rashad**
Models created :
- `User `
  - has_many Comments
  - has_many Posts
- `Comment`
  - belongs_to User
  - belongs_to Post
- `Post`
  - belongs_to User
  - has_many Comments

### CODE REVIEW

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: INVALID
Hey @od-c0d3r ,I invalidated your PR because its showing `error 404` initially  without showing anything but now its showing and working fine.
Kindly resubmit for reivew
here is the screenshot 
[Screenshot 2021-05-22 091200](https://user-images.githubusercontent.com/38242590/119219724-dd1b6c00-bade-11eb-82cf-76d381da8315.png)

**Comment by o-rashad** [comment]
@taiwo2 Thanks for that,
I forget to change the repository visibility 
The error was on my end and I fixed it.

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ♻️
@od-c0d3r  Great job done, I commend your effots, most of the required task is done ,However for this project to be approved changes is required

- [x] your user model should have a validated email (at least for the presence) **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/userValidation.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))
### Kindly fix and request for another review

**Comment by o-rashad** [comment]
@taiwo2 , Thanks for the review ⭐️

- New migration file has been created to add the `email` column in the `users` table.
- Validations added for the new `email` column in `user` model.

**Review by MkrtichSargsyan — APPROVED** [review]
## _Status:_ Approved  :hamster: :rocket:
Hello :wave:.

Awesome job on this milestone.:rocket: Keep it up.
You have met the requirement for this milestone :clap:, 


You can go ahead and merge this branch to the base branch of this repo.

Good luck in your future projects and happy coding :relaxed:

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Comment by o-rashad** [comment]
@MkrtichSargsyan , 
Thanks for the review ⭐️⭐️⭐️
Happy weekend ^^

**Pull request merged**
